        <div class="BoxContent" style="background-image:url(layouts/tibiacom/images/global/content/scroll.gif);">
<h3>What is Tibia?</h3>

Tibia is a free fantasy massively multiplayer online role-playing game (MMORPG). Take the role of a valorous adventurer and explore a mysterious world filled with magic and bravery! Meet up with people from all over the world to live through a whole new game experience!<br><br><br>


<h3>Why Play Tibia?</h3>

<table><tbody><tr><td><img src="layouts/tibiacom/images/global/general/blank.gif" width="10" height="1" border="0"></td><td><table>
<tbody><tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>It's Free!</b><br>No hidden costs, no limited trial phase! Just create an account and play Tibia for as long as you like!</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>Fast and Easy Access!</b><br>Even with a slow internet connection downloading the client is a matter of minutes!</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>Four Character Vocations</b><br>Be a valorous knight, a nimble paladin, a mysterious druid or a mighty sorcerer!</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>Customisable Outfit</b><br>Select from various outfits and give your character the looks of your choice!</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>Character Skills</b><br>Beef up your hero! Characters have a variety of skills that will raise through training.</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>Dozens of Spells</b><br>Fancy some magic? You can fry your enemies with a wide range of deadly spells!</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>Unlimited Character Development</b><br>Characters can be improved on and on. There's just no limit!</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>Massive Game World</b><br>Visit bustling cities, mysterious forests and dreary dungeons. The world of Tibia is huge, and it keeps on growing!</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>Scores of Monsters</b><br>Countless fearsome creatures roam the land. Meet vicious orcs, mighty dragons or deadly demons!</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>Hundreds of Items</b><br>Find hundreds of items. All items are unique and come with their own characteristics and graphics!</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>Quests</b><br>Go on dangerous quests for fame and fortune. All players have equal chances to do quests!</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>Monster Raids and Other Events</b><br>Special game events can happen anytime. There is nothing like a surprise attack on a city to make an adventurer's life exciting!</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>Guilds</b><br>Players can team up in guilds. Join your friends in a powerful Tibia guild!</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>Several Game Modes Available</b><br>Would you like to see more or less player killing? Choose a different game world to play the Tibia you like!</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>Tibia Rules</b><br>A balanced set of rules ensures that Tibia does not sink into anarchy while giving great freedom to players.</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>Tutor System</b><br>Our innovative tutor system will make sure there is always an experienced player to answer if you have a question!</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>Automatic Control of Player Killing</b><br>A sophisticated automatic system makes sure player killing never gets out of hand!</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>Massive Community</b><br>With more than 500,000 players, Tibia is one of the largest games of its kind. Meet people from all over the world!</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>Forum</b><br>The Tibian community never sleeps. Exchange opinions with fellow Tibians on our forum!</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>VIP List</b><br>A sophisticated contact list ensures that you will always know when your friends and enemies are online!</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>Groundbreaking Chat Feature</b><br>Talk to many players at the same time using Tibia's easy-to-use chat feature. Chatting has never been so much fun!</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>Low System Requirements</b><br>Don't worry if your system is a bit advanced in years. Tibia does not require cutting-edge hardware to run!</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>Intuitive and Customisable User Interface</b><br>With context menus and tool tips assisting your every move, Tibia controls are intuitive and easy to learn.</td></tr>
<tr><td valign="top"><img src="layouts/tibiacom/images/global/content/bullet.gif" width="12" height="15" border="0" align="top"></td><td><b>Premium Features Available</b><br>Would you like to take Tibia even further? Make your account Premium to get cool additional features such as rentable houses, brand new spells and areas, and many more!</td></tr>
</tbody></table></td><td><img src="layouts/tibiacom/images/global/general/blank.gif" width="10" height="1" border="0"></td></tr></tbody></table><br>


<center><form action="?subtopic=createaccount" method="post" style="padding:0px;margin:0px;"><div class="BigButton" style="background-image:url(layouts/tibiacom/images/global/buttons/sbutton.gif)"><div onmouseover="MouseOverBigButton(this);" onmouseout="MouseOutBigButton(this);"><div class="BigButtonOver" style="background-image:url(layouts/tibiacom/images/global/buttons/sbutton_over.gif);"></div><input class="ButtonText" type="image" name="Create Account" alt="Create Account" src="layouts/tibiacom/images/global/buttons/_sbutton_createaccount.gif"></div></div></form><center>        </center></center></div>